-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("CTRL + Print")
hl.bind("CTRL + Print", hl.dsp.exec_cmd('grimblast --freeze save area - | satty --filename - --early-exit copy --actions-on-enter save-to-clipboard --copy-command wl-copy --initial-tool arrow'))
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("grimblast --freeze copy area"))
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
hl.unbind("CTRL + SHIFT + R")
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.group.toggle())
hl.unbind("SUPER + SHIFT + T")
