-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 0,
		resize_on_border = false,
	},
	decoration = {
		rounding = 12,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
