# ==================
# STARTUP APPS
# ==================
exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = dms run
exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
exec-once = steam
#exec-once = sleep 1 && __NV_PRIME_RENDER_OFFLOAD=0 __GLX_VENDOR_LIBRARY_NAME=mesa hypridle
exec-once = sleep 3 && keepassxc
exec-once = sleep 5 && /usr/bin/vesktop --ozone-platform=wayland --enable-features=WaylandWindowDecorations %U
exec-once = export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
exec-once = sleep 10 && kdeconnectd
exec-once = sleep 5 && pkill mako
#exec-once = sleep 9 && kdeconnect-indicator

# ## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &
#exec-once = uwsm app -- hypridle